use super::ResumeTemplate;
use printpdf::BuiltinFont;

#[derive(Clone, Copy)]
pub(super) struct PdfTheme {
    pub margin_x: f32,
    pub top_y: f32,
    pub bottom_y: f32,
    pub name_size: f32,
    pub name_line_height: f32,
    pub headline_size: f32,
    pub headline_line_height: f32,
    pub meta_size: f32,
    pub meta_line_height: f32,
    pub body_size: f32,
    pub body_line_height: f32,
    pub section_size: f32,
    pub section_line_height: f32,
    pub section_spacing: f32,
    pub company_size: f32,
    pub company_line_height: f32,
    pub role_size: f32,
    pub role_line_height: f32,
    pub record_spacing: f32,
    pub accent: (f32, f32, f32),
    pub normal_font: BuiltinFont,
    pub bold_font: BuiltinFont,
    pub header_band: bool,
    pub centered_header: bool,
    pub compact_header: bool,
    pub band_color: (f32, f32, f32),
    pub band_rule: (f32, f32, f32),
}

impl PdfTheme {
    pub fn for_template(template: ResumeTemplate) -> Self {
        match template {
            ResumeTemplate::Classic => Self {
                margin_x: 16.0,
                top_y: 282.0,
                bottom_y: 15.0,
                name_size: 20.0,
                name_line_height: 7.2,
                headline_size: 10.5,
                headline_line_height: 4.8,
                meta_size: 8.4,
                meta_line_height: 3.7,
                body_size: 9.2,
                body_line_height: 4.1,
                section_size: 10.5,
                section_line_height: 4.8,
                section_spacing: 3.0,
                company_size: 10.0,
                company_line_height: 4.3,
                role_size: 9.3,
                role_line_height: 4.0,
                record_spacing: 3.0,
                accent: (0.12, 0.22, 0.30),
                normal_font: BuiltinFont::Helvetica,
                bold_font: BuiltinFont::HelveticaBold,
                header_band: false,
                centered_header: true,
                compact_header: false,
                band_color: (0.12, 0.22, 0.30),
                band_rule: (0.67, 0.73, 0.77),
            },
            ResumeTemplate::Clean => Self {
                margin_x: 16.0,
                top_y: 282.0,
                bottom_y: 15.0,
                name_size: 20.0,
                name_line_height: 7.2,
                headline_size: 10.5,
                headline_line_height: 4.8,
                meta_size: 8.4,
                meta_line_height: 3.7,
                body_size: 9.2,
                body_line_height: 4.1,
                section_size: 10.5,
                section_line_height: 4.8,
                section_spacing: 3.0,
                company_size: 10.0,
                company_line_height: 4.3,
                role_size: 9.3,
                role_line_height: 4.0,
                record_spacing: 3.0,
                accent: (0.12, 0.24, 0.32),
                normal_font: BuiltinFont::TimesRoman,
                bold_font: BuiltinFont::TimesBold,
                header_band: false,
                centered_header: false,
                compact_header: false,
                band_color: (0.12, 0.24, 0.32),
                band_rule: (0.55, 0.66, 0.72),
            },
            ResumeTemplate::Compact => Self {
                margin_x: 14.0,
                top_y: 284.0,
                bottom_y: 13.0,
                name_size: 18.0,
                name_line_height: 6.1,
                headline_size: 9.8,
                headline_line_height: 4.2,
                meta_size: 7.9,
                meta_line_height: 3.35,
                body_size: 8.6,
                body_line_height: 3.65,
                section_size: 9.3,
                section_line_height: 4.0,
                section_spacing: 1.8,
                company_size: 9.4,
                company_line_height: 3.85,
                role_size: 8.8,
                role_line_height: 3.6,
                record_spacing: 1.8,
                accent: (0.16, 0.18, 0.20),
                normal_font: BuiltinFont::Helvetica,
                bold_font: BuiltinFont::HelveticaBold,
                header_band: false,
                centered_header: false,
                compact_header: true,
                band_color: (0.16, 0.18, 0.20),
                band_rule: (0.55, 0.58, 0.60),
            },
            ResumeTemplate::Executive => Self {
                margin_x: 18.0,
                top_y: 280.0,
                bottom_y: 16.0,
                name_size: 22.0,
                name_line_height: 7.8,
                headline_size: 11.0,
                headline_line_height: 5.0,
                meta_size: 8.3,
                meta_line_height: 3.8,
                body_size: 9.2,
                body_line_height: 4.15,
                section_size: 10.8,
                section_line_height: 4.9,
                section_spacing: 3.8,
                company_size: 10.2,
                company_line_height: 4.4,
                role_size: 9.4,
                role_line_height: 4.0,
                record_spacing: 3.4,
                accent: (0.09, 0.29, 0.23),
                normal_font: BuiltinFont::Helvetica,
                bold_font: BuiltinFont::HelveticaBold,
                header_band: true,
                centered_header: false,
                compact_header: false,
                band_color: (0.09, 0.21, 0.18),
                band_rule: (0.56, 0.71, 0.62),
            },
            ResumeTemplate::TechMinimalist => Self {
                margin_x: 14.0,
                top_y: 284.0,
                bottom_y: 13.0,
                name_size: 18.5,
                name_line_height: 6.2,
                headline_size: 9.8,
                headline_line_height: 4.2,
                meta_size: 7.8,
                meta_line_height: 3.3,
                body_size: 8.6,
                body_line_height: 3.65,
                section_size: 9.2,
                section_line_height: 4.0,
                section_spacing: 2.0,
                company_size: 9.6,
                company_line_height: 3.9,
                role_size: 8.8,
                role_line_height: 3.6,
                record_spacing: 2.0,
                accent: (0.19, 0.47, 0.78),
                normal_font: BuiltinFont::Courier,
                bold_font: BuiltinFont::CourierBold,
                header_band: false,
                centered_header: false,
                compact_header: true,
                band_color: (0.08, 0.12, 0.16),
                band_rule: (0.19, 0.47, 0.78),
            },
            ResumeTemplate::ModernSplit => Self {
                margin_x: 18.0,
                top_y: 280.0,
                bottom_y: 15.0,
                name_size: 21.0,
                name_line_height: 7.4,
                headline_size: 10.5,
                headline_line_height: 4.8,
                meta_size: 8.0,
                meta_line_height: 3.6,
                body_size: 9.0,
                body_line_height: 4.0,
                section_size: 10.3,
                section_line_height: 4.6,
                section_spacing: 3.0,
                company_size: 10.0,
                company_line_height: 4.2,
                role_size: 9.2,
                role_line_height: 3.9,
                record_spacing: 3.0,
                accent: (0.11, 0.34, 0.50),
                normal_font: BuiltinFont::Helvetica,
                bold_font: BuiltinFont::HelveticaBold,
                header_band: true,
                centered_header: false,
                compact_header: false,
                band_color: (0.11, 0.34, 0.50),
                band_rule: (0.45, 0.68, 0.78),
            },
            ResumeTemplate::ExecutiveBold => Self {
                margin_x: 18.0,
                top_y: 280.0,
                bottom_y: 16.0,
                name_size: 23.0,
                name_line_height: 8.0,
                headline_size: 11.0,
                headline_line_height: 5.0,
                meta_size: 8.2,
                meta_line_height: 3.7,
                body_size: 9.1,
                body_line_height: 4.1,
                section_size: 11.0,
                section_line_height: 5.0,
                section_spacing: 4.0,
                company_size: 10.4,
                company_line_height: 4.4,
                role_size: 9.4,
                role_line_height: 4.0,
                record_spacing: 3.5,
                accent: (0.70, 0.52, 0.18),
                normal_font: BuiltinFont::Helvetica,
                bold_font: BuiltinFont::HelveticaBold,
                header_band: true,
                centered_header: false,
                compact_header: false,
                band_color: (0.07, 0.12, 0.18),
                band_rule: (0.70, 0.52, 0.18),
            },
            ResumeTemplate::Academic => Self {
                margin_x: 18.0,
                top_y: 280.0,
                bottom_y: 17.0,
                name_size: 19.5,
                name_line_height: 7.0,
                headline_size: 10.2,
                headline_line_height: 4.7,
                meta_size: 8.2,
                meta_line_height: 3.7,
                body_size: 9.3,
                body_line_height: 4.25,
                section_size: 10.4,
                section_line_height: 4.8,
                section_spacing: 4.0,
                company_size: 9.8,
                company_line_height: 4.3,
                role_size: 9.2,
                role_line_height: 4.0,
                record_spacing: 3.5,
                accent: (0.35, 0.16, 0.20),
                normal_font: BuiltinFont::TimesRoman,
                bold_font: BuiltinFont::TimesBold,
                header_band: false,
                centered_header: true,
                compact_header: false,
                band_color: (0.35, 0.16, 0.20),
                band_rule: (0.65, 0.48, 0.50),
            },
        }
    }
}
